package com.tbohne.sqlite.annotations.enums;

public enum ForeignKeyDeferMode {
	UNSPECIFIED(""),
	DEFERABLE("DEFERABLE"),
	NOT_DEFERABLE("NOT DEFERABLE"),
	DEFERABLE_INITIALLY_DEFERRED("DEFERABLE INITIALLY DEFERRED"),
	NOT_DEFERABLE_INITIALLY_DEFERRED("NOT DEFERABLE INITIALLY DEFERRED"),
	DEFERABLE_INITIALLY_IMMEDIATE("DEFERABLE INITIALLY IMMEDIATE"),
	NOT_DEFERABLE_INITIALLY_IMMEDIATE("NOT DEFERABLE INITIALLY IMMEDIATE");

	public final String sql;

	ForeignKeyDeferMode(String sql) {
		this.sql = sql;
	}
}
